# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: 04SpringBootConfigPropertiesInputEx-2
my:
  app:
    id: '01'
    code: Test
    data:
    - A
    - B
    - C
    info:
      C1: M1
      C2: M2
      
    pob:
      pid: 15
      pcode: PQR
